### ISSUE TITLE
game theme discussion

### ISSUE THREAD

**Issue by jkarenko** [Pelinakit/gamejam2024#1]
Might be an ongoing process throughout the weekend.
Discuss:

- [x] theme
- [x] goal
- [x] style
- [x] requirements (mvp)
- [x] definition of done

**Comment by malmsat** [comment]
Definition of done: yksi kenttä (mekaniikka), space bubble, jossa kuplat menevät vasemmalta oikealle ja tykillä voi ampua niideen sisältäviä sanoja alas lauseeksi, josta muodostuu "vitsi" josta hahmo tykkää. Kolme hahmoa olisi hyvä. Start menu, kolme bossia joilla oma persoonallisuus ja taustat, joista saa vihjeet niiden huumorintajusta. Sanasto muuttuu myös hahmon mukana. Letkeä rento musiikkirauta, yksi riittää. Jokaisella bossilla omat reagointiäänet. Kaikilla UI-elementeillä ja peli actioneilla oma ääni. Ja nappeihin hoveritehosteet, samoin puhkeamistehoste kupliin. Hahmot: amissiperuna, veleho, meriroisto. Hahmoille naurureaktio ja vakava reaktio. Kun pelin häviää, kellot soi ja joku kuva.
